name: javascript actions
author: phani kumar vangali
description: this is a simple js actions
inputs:
  who_to_greet:
    description: whom to who_to_greet
    default: "world!"
    # required: true

outputs:
  time: 
    description: time of the greeting

runs:
  using: "docker"
  image: 'Dockerfile'
  # entrypoint: 
  args:
    - ${{ inputs.who_to_greet }}
  env:
    HELLO: WORLD
  post-entrypoint: "/cleanup.sh"
  post-if: runner.os == 'linux'
  