name: javascript actions
author: phani kumar vangali
description: this is a simple js actions
inputs:
  who_to_greet:
    description: whom to who_to_greet
    default: "world!"
    required: true

outputs:
  time: 
    description: time of the greeting

runs:
  using: "node24"
  main: "./dist/index.js"
  pre: "setup.js"
  post: "cleanup.js"
  
