name: Cache and Artifacts
on: 
  workflow_dispatch:


jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: cache dependicies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
      - name: install dependicies
        run: npm install