name: caller workflow
on: 
    workflow_dispatch: 
      inputs:
        name:
          description: "name description"
          type: string
          default: "phani"

jobs:
  calling-reuseable-wf:
    uses: ./.github/workflows/reuseable-wf.yaml
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
  wf-output:
    needs: calling-reuseable-wf
    runs-on: ubuntu-18.04
    steps:
      - run: echo ${{ needs.calling-reuseable-wf.outputs.output }}

