name: running docker container inside a job
on: 
    workflow_dispatch

jobs:
    docker:
        runs-on: ubuntu-latest
        container: 
            image: node:trixie-slim
            env:
                API_KEY: "sbgfhrwgfhs"
            ports:
                - 3000
        steps:
            - name: log node
              run: |
                node -v
                ls -a
                echo $API_KEY
            - name: creating a file
              run: echo "simple text" >> simple.txt
            - name: container inside a step
              uses: docker://node:18.16-alpine3.17
              with:
                args: |
                    cat simple.txt
              