name: simple action
on: push

jobs:
    js-actions:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              uses: actions/checkout@v4
            - name: using javascript action
              id: action-output
              uses: kumar5102005/open-issues-action@main
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                title: "this is an new issuse"
                body: "this is the body of the issuse"
                assignees: |
                  phanivangali
            - name: output of the javascript action
              run: echo '${{ steps.action-output.outputs.issuse }}'
            