name: simple action
on: push

jobs:
    js-actions:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              uses: actions/checkout@v4
            - name: log files
              working-directory: ./.github/actions/hello
              run: ls -a
            - name: js-action trail
              id: greet
              uses: ./.github/actions/hello/js-action.yaml
              with:
                who_to_greet: phani
            - name: log the greeting
              run: echo "${{ steps.greet.outputs.time }}"
            - name: log the env var
              run: echo $TIME