name: simple action
on: push

jobs:
    js-actions:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              uses: actions/checkout@v4
            - name: generate joke and send to slack
              uses: ./.github/actions/slack-joke
              with:
                slack_username: phanivangali
                upload-joke: true
                slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
              id: slack_joke
            - name: output of slack joke
              run: echo '${{ steps.slack_joke.outputs.random_joke }}'