name: reuseable workflow
on:
  workflow_call:
      inputs:
        name:
          description: "name description"
          default: "Ali"
          required: true
          type: string
      secrets:
        access-token:
          description: "sercets access token"
          required: true
      outputs:
        output:
          value: ${{ jobs.called-workflow.outputs.output }}
         

jobs:
  called-workflow:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step-3.outputs.branch }}
    steps:
      - name: echo the given inputs
        run: echo "${{ inputs.name }}"
      - name: echo sercets
        run: echo "${{ secrets.access-token }}"
      - name: output step
        id: step-3
        run: echo 'branch=${{github.action_repository}}' >> $GITHUB_OUTPUT
      - run: echo ${{steps.step-3.outputs.branch}}
